package au.edu.unsw.soacourse.stockmarketdata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-02T00:41:32.444+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "StockMarketData", 
                  wsdlLocation = "file:/home/jose/workspace2/comp9322/assignment1/StockMarketData/src/main/resources/wsdl/StockMarketData.wsdl",
                  targetNamespace = "http://stockmarketdata.soacourse.unsw.edu.au") 
public class StockMarketData_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://stockmarketdata.soacourse.unsw.edu.au", "StockMarketData");
    public final static QName StockMarketDataSOAP = new QName("http://stockmarketdata.soacourse.unsw.edu.au", "StockMarketDataSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jose/workspace2/comp9322/assignment1/StockMarketData/src/main/resources/wsdl/StockMarketData.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StockMarketData_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/jose/workspace2/comp9322/assignment1/StockMarketData/src/main/resources/wsdl/StockMarketData.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StockMarketData_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StockMarketData_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockMarketData_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StockMarketData_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StockMarketData_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StockMarketData_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns StockMarketData
     */
    @WebEndpoint(name = "StockMarketDataSOAP")
    public StockMarketData getStockMarketDataSOAP() {
        return super.getPort(StockMarketDataSOAP, StockMarketData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockMarketData
     */
    @WebEndpoint(name = "StockMarketDataSOAP")
    public StockMarketData getStockMarketDataSOAP(WebServiceFeature... features) {
        return super.getPort(StockMarketDataSOAP, StockMarketData.class, features);
    }

}
