package au.edu.unsw.soacourse.stockmarketdata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-02T20:12:38.793+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "StockMarketDataImplService", 
                  wsdlLocation = "http://192.168.99.100:8888/StockMarketData/StockMarketData?wsdl",
                  targetNamespace = "http://stockmarketdata.soacourse.unsw.edu.au/") 
public class StockMarketDataImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://stockmarketdata.soacourse.unsw.edu.au/", "StockMarketDataImplService");
    public final static QName StockMarketDataImplPort = new QName("http://stockmarketdata.soacourse.unsw.edu.au/", "StockMarketDataImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.99.100:8888/StockMarketData/StockMarketData?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StockMarketDataImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.99.100:8888/StockMarketData/StockMarketData?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StockMarketDataImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StockMarketDataImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockMarketDataImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StockMarketDataImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StockMarketDataImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StockMarketDataImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns StockMarketData
     */
    @WebEndpoint(name = "StockMarketDataImplPort")
    public StockMarketData getStockMarketDataImplPort() {
        return super.getPort(StockMarketDataImplPort, StockMarketData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockMarketData
     */
    @WebEndpoint(name = "StockMarketDataImplPort")
    public StockMarketData getStockMarketDataImplPort(WebServiceFeature... features) {
        return super.getPort(StockMarketDataImplPort, StockMarketData.class, features);
    }

}
