
package au.edu.unsw.soacourse.stockmarketdata;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-02T20:12:38.789+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "yahooExchangeRateFault", targetNamespace = "http://stockmarketdata.soacourse.unsw.edu.au")
public class YahooExchangeRateFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.stockmarketdata.ServiceFaultType yahooExchangeRateFault;

    public YahooExchangeRateFaultMsg() {
        super();
    }
    
    public YahooExchangeRateFaultMsg(String message) {
        super(message);
    }
    
    public YahooExchangeRateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public YahooExchangeRateFaultMsg(String message, au.edu.unsw.soacourse.stockmarketdata.ServiceFaultType yahooExchangeRateFault) {
        super(message);
        this.yahooExchangeRateFault = yahooExchangeRateFault;
    }

    public YahooExchangeRateFaultMsg(String message, au.edu.unsw.soacourse.stockmarketdata.ServiceFaultType yahooExchangeRateFault, Throwable cause) {
        super(message, cause);
        this.yahooExchangeRateFault = yahooExchangeRateFault;
    }

    public au.edu.unsw.soacourse.stockmarketdata.ServiceFaultType getFaultInfo() {
        return this.yahooExchangeRateFault;
    }
}
